---
- hosts: all
  become: true
  tasks:


    - name: remove folder
      file:
        path: /home/ansible/my-hadoop-install
        state: absent

    - name: install tools
      apt: name={{item}} state=present update_cache=yes
      with_items:
              - openjdk-8-jdk-headless


    - name: Create Folder
      file: 
       path: /home/ansible/my-hadoop-install
       owner: ansible 
       mode: 0755 
       state: directory


    - name: Download hadoop
      get_url:
         url: http://apache.claz.org/hadoop/common/hadoop-3.1.1/hadoop-3.1.1.tar.gz
         dest: /home/ansible/my-hadoop-install
         mode: 0755


    - name: Unarchive File
      unarchive:
        src: /home/ansible/my-hadoop-install/hadoop-3.1.1.tar.gz
        dest: /home/ansible/my-hadoop-install
        remote_src: yes     
