---
- hosts: webserver
  become: true
  tasks:
     - name: install apache2
       apt: name={{item}} state=present update_cache=yes
       # will fire of foreach on withitems by passing item param to be installed
       with_items:
              - apache2
              - libapache2-mod-wsgi
              - python-pip
              - python-virtualenv
